### ISSUE TITLE
sa_get_random_moveable_vertex assumes verticies are ordered

### ISSUE THREAD

**Issue by robert-hardwick** [project-rig/rig_c_sa#7]
Ran into a Segmentation Fault when i switched over to the C Kernel and manged to narrow it down to 

sa_remove_vertex_from_chip(state, va)  trying to remove a non-movable vertex which was never added to the chip and therefore is not present to be removed.

For some reason line 316 didn't assert, but instead segfaulted when *next_ptr is dereferenced (will try and get more debug around why this assert didn't fail )
		assert((*next_ptr)->next != NULL);  // The vertex *must* be present!

What causes is this is the sa_get_random_movable_vertex returning a non-movable vertex due to the random selection expecting the vertices to be ordered with movable vertices at the start of the list. In my case the vertices were shuffled and it sometimes returned a movable vertex and when it returned a non-movable vertex it would later segfault in the function sa_remove_vertex_from_chip as mentioned above.

sa_vertex_t *sa_get_random_movable_vertex(const sa_state_t *state) {
	// TODO: Use a propper random scheme...
	return state->vertices[rand() % state->num_movable_vertices];
}

Workaround is to order the vertices in rig python code before calling down to C. However a robust random selection in C is the preferred solution.

**Comment by mossblaser** [comment]
Hey there! Thanks for the very detailed bug report! Glad to see this is still getting used :).

I'm curious about the sorting issue. The header file mentions that the C library expects the verticies to be sorted before it gets them (so if they're not arriving in the right order this would be a bug on the python side), could there be something amiss in the Python side leading these to be out of order? From dim memory the C kernel's python code is supposed  to sort all that ordering stuff out before the C side gets a go at it...

The assertion not doing what it is supposed to is also a bit odd. Maybe the python driven build process disables assertion checking? I was so happy to find setup tools building the C stuff for me and with all the right flags for CFFI I stopped asking questions about exactly how it was building it perhaps a bit too soon...

I'm afraid I'm away for the weekend so don't really have a proper machine to test this on... Do you happen to have a shortish test program which triggers the bug?

**Comment by robert-hardwick** [comment]
Hi. Ok i've just seen the header file, yep i didn't notice that, probably because i was just using rig as-is and not expecting rig to be the problem since the rig python kernel worked ok.

Now that i've seen that i think then the bug is in the rig c_kernel.py python code. Infact the workaround that i devised was to sort the vertices in this file before calling down to rig_c_sa.

I can probably devise a short test program to illustrate the bug at somepoint this week.

If you'd like you can close this issue and we can re-raise an issue in rig?

Rob

**Comment by mossblaser** [comment]
I think you're right about the source of the bug being the non sorting in python. I'm flabbergasted and disappointed that this fundamental problem hasn't shown itself earlier or caught by the tests, never mind that it exists in the first place...

I'll have another closer look tomorrow on my way into work...

Many thanks and my apologies.

**Comment by mossblaser** [comment]
Hi there @robert-hardwick. Thanks again for finding this, the fix to rig has now been released and should be available from v2.4.1 in pypi. Please let me know if you run into any other difficulties and thanks again for help!
